Style/IfUnlessModifier:
  MaxLineLength: 125

Metrics/LineLength:
  Max: 125

Metrics/MethodLength:
  Max: 100

Metrics/ClassLength:
  Max: 500

Style/Encoding:
  Enabled: false
  
Style/GuardClause:
  Enabled: false
  
Style/MultilineTernaryOperator:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  
Metrics/PerceivedComplexity:
  Enabled: false

